version: "3.6"

# dump: docker-compose exec -T postgres pg_dump --host postgres --format=tar --user postgres postgres > db_$(date +%Y%m%d-%H%M%S).tar
# load: docker-compose exec -T postgres pg_restore -U postgres -d postgres --exit-on-error < db_2018-08-08.tar


services:

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --username=postgres --dbname=postgres
      
  pgweb:
    image: sosedoff/pgweb
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    expose:
      - 8081
      
volumes:
  pg-data:
